feat: add origin
LedgerHQ/exchange-sdk pull request #82
Opened 2024-09-17 03:12 UTC by chrisduma-ledger

2024-09-17 09:15 UTC, sarneijim requested changes
Please, avoid code duplication.
If you want to change the name must be "exchange003" instead, and if you are going to change it you must change it across all the file.

2024-09-17 09:22 UTC, CremaFR approved these changes

2024-09-17 10:44 UTC, chrisduma-ledger commented
@sarneijim 
> and if you are going to change it you must change it across all the file.

As I have written in Slack, I will add it for the whole file if the teams agree with the proposal 
<img width="356" alt="Screenshot 2024-09-17 at 13 43 11" src="https://github.com/user-attachments/assets/9e683ceb-4b2c-49c9-b962-51ba89d16bac">

> If you want to change the name must be "exchange003" instead

If we use `exchange` as a name, then we will not be able to differentiate between apps, and the swap team needs `003` to not display, we want it to display, please make a proposal for the issue.

2024-09-18 07:30 UTC, sprohaszka-ledger reviewed
A few comments. The one that bother me most is the dependency one.

2024-09-18 07:30 UTC, sprohaszka-ledger commented on lib/src/error.ts
> +import { ErrorOrigin } from "./sdk";
This dependency create a cycle one between `error.ts` and `sdk.ts`.
We can either replace the parameter as a string or if you want to enforce the use of an enum, extract this enum definition in a different file.

2024-09-18 07:30 UTC, sprohaszka-ledger commented on lib/src/sdk.ts
> +export enum ErrorOrigin {
Why don't reuse `ExchangeType`? It seems they both serve the same purpose (characterize exchange transaction).

2024-09-18 07:30 UTC, sprohaszka-ledger commented on lib/src/sdk.ts
> + * Under the hood, it relies on the WalletAPI.
The link didn't work?

2024-09-18 10:02 UTC, sprohaszka-ledger approved these changes
LGTM

2024-09-18 10:46 UTC, sarneijim approved these changes
THANK YOU!

2024-09-18 11:05 UTC, merged